### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ds8k** [jorgenhenrichsen/SwiftAudio#107]
I'm using `react-native-track-player`, which uses this library for iOS audio playback. I've run into an issue that I can't seem to find the root cause of - my app is crashing when trying to add tracks to it suddenly. When it crashes, I get this error:

```
Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

The code it's telling me that caused the crash is in `NowPlayingInfoCenter.swift`:
```
    public func set(keyValue: NowPlayingInfoKeyValue) {
        _info[keyValue.getKey()] = keyValue.getValue()
        self._infoCenter.nowPlayingInfo = _info
    }
```

Looking through the trace on the right of Xcode, it looks like the call to update the now playing duration is what's causing this? Would it be possible to guard these functions from setting invalid values?

```
    public func set(keyValue: NowPlayingInfoKeyValue) {
        let key = try? keyValue.getKey()
        let value = try? keyValue.getValue()
        
        if (key != nil && value != nil) {
            _info[keyValue.getKey()] = keyValue.getValue()
            self._infoCenter.nowPlayingInfo = _info
        }
    }
```

**Comment by JhonnyTawk** [comment]
I am having this issue also

**Comment by Igorsnaki** [comment]
also facing the same issue. 

@ds8k hi. did you managed to fix it? 
Any suggestion?
