### ISSUE TITLE
How to use with local files?

### ISSUE THREAD

**Issue by gerritwh** [jorgenhenrichsen/SwiftAudio#43]
Could you please give an example on how to use the player with local mp3 file? 

That’ll be awesome!

**Comment by jorgenhenrichsen** [comment]
Sure 👍
Here is an example when using the DefaultAudioItem struct.
```swift
let url = URL(fileURLWithPath: "PathToYourSoundFile")
let item = DefaultAudioItem(audioUrl: url, sourceType: .file)
try? audioPlayer.load(item)
```
This of course requires you to find the correct path to your mp3 file.

**Comment by TheM4hd1** [comment]
Just a note, don't include ```scheme``` in your path
It's wrong: ```file:///var/container/......./music.mp3```, you have to remove ```file://```

**Comment by gerritwh** [comment]
Alright. Works perfectly. 

I’m getting the path now like this: 

`let path: String = Bundle.main.path(forResource: "soundfile", ofType: "mp3")! `

Thank you so much.
