### ISSUE TITLE
Crash on loading items immediately

### ISSUE THREAD

**Issue by TheM4hd1** [jorgenhenrichsen/SwiftAudio#45]
I've got weird crashes when trying to loading items one after one in ```.stream``` sourceType.
I'm using ```AudioPlayer``` and not ```QueuedAudioPlayer```

I've checked a few things and it seems the problem is with removing observer and sometimes the ```AVPlayerItem``` gets deallocated but the observers for ```.duration``` and ```.loadedTimeRanges```` still registered.

Image 1:

![Screen Shot 2019-03-16 at 12 27 12 PM](https://user-images.githubusercontent.com/31998234/54473532-4102c580-47ee-11e9-9843-687c2910768a.png)

Image 2:

![Screen Shot 2019-03-16 at 12 57 18 PM](https://user-images.githubusercontent.com/31998234/54473533-452ee300-47ee-11e9-9426-87e9628bcbe9.png)

**NOTE**

**the problem occurred when I've tried to load items immediately one after one.**
 its ok when I let them to get ```.ready state``` before loading another-one.

**Comment by jorgenhenrichsen** [comment]
Yep, looks like a problem with registering of the observer. I'll look into this when I have time!

**Comment by jorgenhenrichsen** [comment]
@TheM4hd1 Could you supply some code to describe what you do to make it crash? I haven't been able to reproduce the bug yet.

**Comment by TheM4hd1** [comment]
sorry for delay, the problem occurred when I was trying to load items immediately in ```stream``` mode one after one, without letting them to load completely. 
I fixed this error by loading items in a ```background``` thread. it works fine now
still testing it and will let you know if the issue still exists.
