### ISSUE TITLE
Remove current item?

### ISSUE THREAD

**Issue by rawandahmad698** [jorgenhenrichsen/SwiftAudio#46]
This is not an issue!

Question: How do i remove the current item (song) that is about to play? 

I'm just curious.

**Comment by jorgenhenrichsen** [comment]
Hey! Hope I understand you correctly here.

Calling `stop()` on the player will set the current item to nil and stop the player.
If you are using a `QueuedAudioPlayer` and want to remove all upcoming items you can call `removeUpcomingItems()`.

I see now that there is no convenient way to remove the next item in the queue, so will look into that 👍

**Comment by jorgenhenrichsen** [comment]
Made a PR that makes this more convenient: #47
