### ISSUE TITLE
Playing local audio file

### ISSUE THREAD

**Issue by rawandahmad698** [jorgenhenrichsen/SwiftAudio#48]
Hey there. 

I'm trying to work with SwiftAudio. I have downloaded a 3MB music using URLSession and i can see it in the simulator folders, 

My URL looks something like this:

`file:///Users/Adam/Library/Developer/CoreSimulator/Devices/D38BAB08-846E-4172-9DB1-8D3567F6E10E/data/Containers/Data/Application/DE2FF955-B927-4542-A290-4DE550B6C53D/Library/Caches/Digger/mySongByAdam.mp3`

Now, using `loadItem` won't work for me. 

Also as mentioned in issue [#43](https://github.com/jorgenhenrichsen/SwiftAudio/issues/43) that i SHOULDN'T include my `scheme` URL, But i do not know how to remove the file:/// or get an appropriate index of the file.

Edit:
Testing it on iPhone X iOS(12.0)
With this file `var/mobile/Containers/Data/Application/2BC8BB07-D24C-4625-B2F8-C444F687994D/Library/Caches/Digger/flowerAdam.mp3`
Still doesn't work

**Comment by jorgenhenrichsen** [comment]
To get a local file like you have there you could do:
```swift
let fileName = "mySongByAdam.mp3"
let url = FileManager.default
                     .urls(for: .documentDirectory, in: .userDomainMask)[0]
                     .appendingPathComponent(filename)
var urlString = url.absoluteString
urlString.removeSubrange(str.range(of: "file://")!)
```
In my experience you have to remove the `"file://"` when playing downloaded files on the simulator. I haven't properly tested that on a real device, but could be that it is not needed there.

Let me now if the above snippet works for you 👍

**Comment by rawandahmad698** [comment]
Thank you so much man, this really helped me! Now it’s working
