### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [jorgenhenrichsen/SwiftAudio#50]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by rawandahmad698** [comment]
Very nice, thanks for contributing to SwiftAudio

**Comment by jorgenhenrichsen** [comment]
Sure 👍

**Comment by anharismail** [comment]
Hi @jorgenhenrichsen , I've designed a logo for this project. This logo concept inspired from audio idea (headphone) and bird idea from Swift Bird. I also didn't use or modify swift logo to this logo to avoiding copyright issues from the Swift. 

Very welcome if you have any opinions or suggestions about it.

Regards.

![SwiftAudio Ver  1](https://user-images.githubusercontent.com/37614260/59188846-d1a93180-8ba2-11e9-8bf5-ce39f1124252.png)

**Comment by rawandahmad698** [comment]
Wow. Superb design

**Comment by jorgenhenrichsen** [comment]
That looks great! Could you send the individual files for each style?
If you want to make a PR just put the files in a folder in the root directory of the project: `/Images/`.

**Comment by anharismail** [comment]
Hi @jorgenhenrichsen @rawandahmad698 , Thanks for all your response. Very Glad to have it.

Then, I've made pull request about the logo.

I also provide all editable files here: https://drive.google.com/drive/u/1/folders/1nM2dWmc_Ixa3gpVEnmUNsVenAQJqeQmG

**Comment by jorgenhenrichsen** [comment]
Great! Merged the PR now ✔
Closing this.
