### ISSUE TITLE
how to track milli-seconds elapsed time

### ISSUE THREAD

**Issue by murad1981** [jorgenhenrichsen/SwiftAudio#52]
currently the player track the state every second of playback, however, I couldn't find a way to track the change every milli-second, so that the playback UI component (slider or UIProgressView for ex.) will update the visual track smoother than a 1 second threshold.

**Comment by jorgenhenrichsen** [comment]
For now you can set `player.timeEventFrequency = .everyQuarterSecond` and try to animate your progress indicator. Might not achieve exactly what you want, but I will later add a case to `TimeEventFrequency` where you can pass in a custom `CMTime` and receive updates as often as you want 👍
