### ISSUE TITLE
cannot play audio after reaching "ended" state

### ISSUE THREAD

**Issue by murad1981** [jorgenhenrichsen/SwiftAudio#53]
I cannot play the same audio file again after it ended with end reason: playedUntilEnd, is there a way to play it again ?

**Comment by jorgenhenrichsen** [comment]
Can you call `player.load(item:)`? Or do you mean a repeat function that will repeat a track when it is completed?

**Comment by murad1981** [comment]
I don't mean a continuous playback, I just want to play it again with a second play button press.

**Comment by murad1981** [comment]
> Can you call `player.load(item:)`? Or do you mean a repeat function that will repeat a track when it is completed?

I can call player.load(item:) but it will reload the item again and there will be a delay, instead the player must play the same item from cache.

**Comment by jorgenhenrichsen** [comment]
Ah, I get it.  Loading the item will probably result in a delay, as there is no caching system right now. This really ties into #39.

If you want to just replay the current item, you could maybe call `seek(to: 0)` when the item has played to the end? This way when calling `play()` again, it will start over.
