### ISSUE TITLE
calling load(item:PlayWhenReady) doesn't trigger play the second time

### ISSUE THREAD

**Issue by murad1981** [jorgenhenrichsen/SwiftAudio#58]
Calling `load(item:playWhenReady:)` method will not trigger `play` method of the wrapper after adding item(s) to the `QueuedPlayer`, that means when I add items first then play any of them, if we decide to add more items or just load a new item later, **the view sometimes freezes** and **the item is not played**.
After some investigation, it turned out to be `load(from:, playWhenReady:)` method, it must not call `avPlayer.replaceCurrentItem(with:)` on the main thread, rather, it must be called using `asset.loadValuesAsynchronously(forKeys:)` method (as detailed in [the second answer here](https://stackoverflow.com/questions/7701212/avplayer-freezes-the-app-at-the-start-of-buffering-an-audio-stream)).

**Comment by jorgenhenrichsen** [comment]
This should be solved now by #51 .
