### ISSUE TITLE
The player will not play track after disconnect/connect to the internet

### ISSUE THREAD

**Issue by murad1981** [jorgenhenrichsen/SwiftAudio#59]
In case I disconnected the device from the internet, and hit play to play the track nothing happens and this is the expected behavior, but I reconnect to the internet and hit play again the audio file will not play as expected.
I can reproduce this bug in your example project.

**Comment by jorgenhenrichsen** [comment]
This will be partly fixed by #60 . You will, however, be required to load the item again after the disconnect.

**Comment by jorgenhenrichsen** [comment]
Check out the example app in v0.10.0, it contains an example of how to handle a network error. In a future release, this might be handled more gracefully by the audio player itself.
