### ISSUE TITLE
Repeat Audio 

### ISSUE THREAD

**Issue by wawilliams003** [jorgenhenrichsen/SwiftAudio#72]
Hello thanks for this wonderful library, do you planned to add any repeating features? either repeat one or all audios? If not I would appreciate if you could point me to the right logic to figure it out. Thank you!

**Comment by jorgenhenrichsen** [comment]
Hey, this is is a feature that probably will be included sometime in the future.
Meanwhile, this is one possible solution:
```swift
var player = QueuedAudioPlayer()
player.addItems([
    audioItem1,
    audioItem2,
    audioItem3
]]

player.event.playbackEnd.addListener(self, handlePlaybackEnd)

func handlePlaybackEnd(data: AudioPlayer.PlaybackEndEventData) {
    if data == .playedUntilEnd {
        try? player.previous()
    }
}
```
This will just step back the queue whenever a track is finished. If you want to enable/disable the repeat function you can just add a boolean and check that whenever a track finishes.

**Comment by wawilliams003** [comment]
Thank you for your response, unfortunately, this suggestion doesn't work. The app crashes after playback ends with error:
**reason: 'Cannot remove an observer <SwiftAudio.AVPlayerObserver 0x6000035f2840> for the key path "timeControlStatus" from <AVPlayer 0x6000022b8800> because it is not registered as an observer.**

**This is what I tried**
` func handlePlaybackEnd(data: AudioPlayer.PlaybackEndEventData) {
        if data == .playedUntilEnd {
            print("playback end")
            if repeatOn {
               // audioController.player.pause()
                try? audioController.player.previous()
               // audioController.player.play()
            }else {
                try? audioController.player.next()
            }
        }
    }`

**Comment by jorgenhenrichsen** [comment]
Okay I see. What version of SwiftAudio are you using?

**Comment by wawilliams003** [comment]
I am using the  latest version.

**Comment by jorgenhenrichsen** [comment]
Is it happening when the `player.previous()` is triggered? Or `player.next()`?

**Comment by wawilliams003** [comment]
It happened when the player.prevous is triggered 

Regards,
Wayne

**Comment by jorgenhenrichsen** [comment]
Okay, for me the method kinda worked, but it is not optimal. I am gonna tag this as an enhancement since a repeat function is useful, so it will be implemented when I get around to it 👍

**Comment by wawilliams003** [comment]
Couldn’t get it to work, what I did was 
Get the current item. When the current time finished playing I load that current in the Queue. This worked for me. Keep up the great work.

Regards,
Wayne

**Comment by jorgenhenrichsen** [comment]
Thanks, yeah that seems like a good solution for now 👍

**Comment by wawilliams003** [comment]
Here’s the app feel free to check it out and see your wonderful library at work, thank you again. 
https://itunes.apple.com/us/app/inspyr-daily-inspiration/id1382904920?mt=8

Regards,
Wayne

**Comment by jorgenhenrichsen** [comment]
Nice, good job 👍

**Comment by JhonnyTawk** [comment]
@wawilliams003 can you give me pointers how did you add the shuffle and the repeat button?
Thank you
