### ISSUE TITLE
Is it possible to load song image from a given url?

### ISSUE THREAD

**Issue by JhonnyTawk** [jorgenhenrichsen/SwiftAudio#75]
I want to load the song image from my database.
instead of
 `DefaultAudioItem(audioUrl: <String>, artist: <String?>, title: <String?>, albumTitle: <String?>, sourceType: <SourceType>, artwork: <UIImage?>)
`
can I use 

`DefaultAudioItem(audioUrl: <String>, artist: <String?>, title: <String?>, albumTitle: <String?>, sourceType: <SourceType>, artwork: **<ImageLink?>)**

`

**Comment by jorgenhenrichsen** [comment]
Hey, 
In this case, you should implement the `AudioItem`- protocol in your own subclass and use that.
There you can implement the `getArtwork(_ handler: @escaping (UIImage?) -> Void)` - method, where you can fetch the image from your database, and then give it to the handler.
