### ISSUE TITLE
[Question] Is Remote Notifications actually needed?

### ISSUE THREAD

**Issue by curiousdustin** [jorgenhenrichsen/SwiftAudio#79]
I am using `SwiftAudio` as part of `react-native-track-player`. I am trying to track down some issues related to the lock screen controls and background loading. https://github.com/react-native-kit/react-native-track-player/issues/709

So far, I don't think the issue is with `SwiftAudio`. However, I was looking at differences between `SwiftAudio` example and `react-native-track-player` example, and noticed that `SwiftAudio` has the Remote Notifications background mode enabled.

Is this really necessary?

The `SwiftAudio` docs say to enable it as part of supporting remote commands.
```App Settings -> Capabilites -> Background Modes -> Check 'Remote notifications'```

However, all the Apple docs I can find on this setting are referring to a completely different type of notification, related to alerting the app of new content to download.

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW10

Can you explain, if you have some time? Thanks!

**Comment by jorgenhenrichsen** [comment]
You are right, I did not spot that! Just a mistake on my part, I will remove the recommendation to turn them on. The only background mode that is needed is the Audio, Airplay, and Picture in Picture mode, for playback.

**Comment by curiousdustin** [comment]
👍  Thank you very much for your quick reply :)
