### ISSUE TITLE
iOS 13 won't play next track in Queue Automatic!

### ISSUE THREAD

**Issue by SalarDastan** [jorgenhenrichsen/SwiftAudio#82]
**Describe the bug**
iOS 13 won't play next track in Queue Automatic!

**To Reproduce**
just create an array with DefaultAudioItem and then playsong.

**Expected behavior**
after a track ends automatic play next track in queue

**Screenshots**

**Desktop (please complete the following information):**
iOS
xCode 11-beta7

**Smartphone (please complete the following information):**
iOS13 beta 8 [Simulator and iPhone 6s real device]

**Comment by rawandahmad698** [comment]
I'm not on iOS 13 or macOS Catalina, when they're available globally, i'd be happy to take a look

**Comment by jorgenhenrichsen** [comment]
Are you running the example application? It works for me on a iPhone 11 simulator in Xcode 11.0 (11A419c).

**Comment by SalarDastan** [comment]
thanks to u, looks like apple fixed it in iOS 13 release date.
if there is a bug i'll let u know.
