### ISSUE TITLE
playing current time and duration get wrong 

### ISSUE THREAD

**Issue by DangarOpenxcell** [jorgenhenrichsen/SwiftAudio#85]
**Describe the bug**

**To Reproduce**
If needed, include code examples for the problem or steps to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.7.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator iPhone6 ...]
 - Version [e.g. 0.7.0]

**Additional context**

**Comment by jorgenhenrichsen** [comment]
You have to provide more details to explain your problem.

**Comment by bmp123** [comment]
have same issue
